apiVersion : v1
kind: Deployment
metadata:
  name: nginx
spec:
  labels:
    app: nginx
spec:
  replicas: 1  # the number of pods
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx-image
          ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        - containerPort: 22
          name: ssh
        imagePullPolicy: Never
        securityContext:
          privileged: true
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
    - name: https
      port: 443
    - name: ssh
      port: 22