apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
        containers:
          - name: phpmyadmin
            image: phpmyadmin
            imagePullPolicy: Never
            ports:
            - containerPort: 5000


---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: wp
spec:
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  loadBalancerIP: 192.168.99.101
  selector:
    app: phpmyadmin
  ports:
  - name: http
    port: 5000
