apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      name: telegraf
      labels:
        app: telegraf
    spec:
        containers:
          - name: telegraf-container
            image: telegraf
            imagePullPolicy: Never
            volumeMounts:
              - name: docker-socket
                mountPath: /var/run/docker.sock
        volumes:
          - name: docker-socket
            hostPath:
              path: /var/run/docker.sock
              type: Socket
---
apiVersion: v1
kind: Service
metadata:
  name: telegraf
spec: 
  selector:
    app: telegraf
  ports:
  - port: 8125
    targetPort: 8125